#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisPatch
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TjData")]
	public partial class DataClassesTjDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertHYDWDMB(HYDWDMB instance);
    partial void UpdateHYDWDMB(HYDWDMB instance);
    partial void DeleteHYDWDMB(HYDWDMB instance);
    partial void InsertGZRY(GZRY instance);
    partial void UpdateGZRY(GZRY instance);
    partial void DeleteGZRY(GZRY instance);
    partial void InsertTJ_TJDJB(TJ_TJDJB instance);
    partial void UpdateTJ_TJDJB(TJ_TJDJB instance);
    partial void DeleteTJ_TJDJB(TJ_TJDJB instance);
    #endregion
		
		public DataClassesTjDataContext() : 
				base(global::HisPatch.Properties.Settings.Default.TjDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTjDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTjDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTjDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTjDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HYDWDMB> HYDWDMB
		{
			get
			{
				return this.GetTable<HYDWDMB>();
			}
		}
		
		public System.Data.Linq.Table<GZRY> GZRY
		{
			get
			{
				return this.GetTable<GZRY>();
			}
		}
		
		public System.Data.Linq.Table<TJ_TJDJB> TJ_TJDJB
		{
			get
			{
				return this.GetTable<TJ_TJDJB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="futian_user.HYDWDMB")]
	public partial class HYDWDMB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BH;
		
		private string _MC;
		
		private string _DWFZR;
		
		private string _LXDH;
		
		private string _CZDH;
		
		private string _LXDZ;
		
		private string _YZBM;
		
		private System.Nullable<char> _QYXZ;
		
		private string _YWYY;
		
		private string _YHZH;
		
		private System.Nullable<int> _JZRS;
		
		private System.Nullable<double> _LJZFJE;
		
		private System.Nullable<double> _LJZCJE;
		
		private string _BZ;
		
		private string _ZHXGR;
		
		private System.Nullable<System.DateTime> _ZHXGRQ;
		
		private string _LB;
		
		private System.Nullable<int> _BZRS;
		
		private string _PYJM;
		
		private string _WBJM;
		
		private System.Nullable<char> _QYBZ;
		
		private System.Nullable<char> _WJBZ;
		
		private EntitySet<TJ_TJDJB> _TJ_TJDJB;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBHChanging(string value);
    partial void OnBHChanged();
    partial void OnMCChanging(string value);
    partial void OnMCChanged();
    partial void OnDWFZRChanging(string value);
    partial void OnDWFZRChanged();
    partial void OnLXDHChanging(string value);
    partial void OnLXDHChanged();
    partial void OnCZDHChanging(string value);
    partial void OnCZDHChanged();
    partial void OnLXDZChanging(string value);
    partial void OnLXDZChanged();
    partial void OnYZBMChanging(string value);
    partial void OnYZBMChanged();
    partial void OnQYXZChanging(System.Nullable<char> value);
    partial void OnQYXZChanged();
    partial void OnYWYYChanging(string value);
    partial void OnYWYYChanged();
    partial void OnYHZHChanging(string value);
    partial void OnYHZHChanged();
    partial void OnJZRSChanging(System.Nullable<int> value);
    partial void OnJZRSChanged();
    partial void OnLJZFJEChanging(System.Nullable<double> value);
    partial void OnLJZFJEChanged();
    partial void OnLJZCJEChanging(System.Nullable<double> value);
    partial void OnLJZCJEChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnZHXGRChanging(string value);
    partial void OnZHXGRChanged();
    partial void OnZHXGRQChanging(System.Nullable<System.DateTime> value);
    partial void OnZHXGRQChanged();
    partial void OnLBChanging(string value);
    partial void OnLBChanged();
    partial void OnBZRSChanging(System.Nullable<int> value);
    partial void OnBZRSChanged();
    partial void OnPYJMChanging(string value);
    partial void OnPYJMChanged();
    partial void OnWBJMChanging(string value);
    partial void OnWBJMChanged();
    partial void OnQYBZChanging(System.Nullable<char> value);
    partial void OnQYBZChanged();
    partial void OnWJBZChanging(System.Nullable<char> value);
    partial void OnWJBZChanged();
    #endregion
		
		public HYDWDMB()
		{
			this._TJ_TJDJB = new EntitySet<TJ_TJDJB>(new Action<TJ_TJDJB>(this.attach_TJ_TJDJB), new Action<TJ_TJDJB>(this.detach_TJ_TJDJB));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BH", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BH
		{
			get
			{
				return this._BH;
			}
			set
			{
				if ((this._BH != value))
				{
					this.OnBHChanging(value);
					this.SendPropertyChanging();
					this._BH = value;
					this.SendPropertyChanged("BH");
					this.OnBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string MC
		{
			get
			{
				return this._MC;
			}
			set
			{
				if ((this._MC != value))
				{
					this.OnMCChanging(value);
					this.SendPropertyChanging();
					this._MC = value;
					this.SendPropertyChanged("MC");
					this.OnMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWFZR", DbType="VarChar(10)")]
		public string DWFZR
		{
			get
			{
				return this._DWFZR;
			}
			set
			{
				if ((this._DWFZR != value))
				{
					this.OnDWFZRChanging(value);
					this.SendPropertyChanging();
					this._DWFZR = value;
					this.SendPropertyChanged("DWFZR");
					this.OnDWFZRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXDH", DbType="VarChar(16)")]
		public string LXDH
		{
			get
			{
				return this._LXDH;
			}
			set
			{
				if ((this._LXDH != value))
				{
					this.OnLXDHChanging(value);
					this.SendPropertyChanging();
					this._LXDH = value;
					this.SendPropertyChanged("LXDH");
					this.OnLXDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CZDH", DbType="VarChar(16)")]
		public string CZDH
		{
			get
			{
				return this._CZDH;
			}
			set
			{
				if ((this._CZDH != value))
				{
					this.OnCZDHChanging(value);
					this.SendPropertyChanging();
					this._CZDH = value;
					this.SendPropertyChanged("CZDH");
					this.OnCZDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LXDZ", DbType="VarChar(32)")]
		public string LXDZ
		{
			get
			{
				return this._LXDZ;
			}
			set
			{
				if ((this._LXDZ != value))
				{
					this.OnLXDZChanging(value);
					this.SendPropertyChanging();
					this._LXDZ = value;
					this.SendPropertyChanged("LXDZ");
					this.OnLXDZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YZBM", DbType="Char(6)")]
		public string YZBM
		{
			get
			{
				return this._YZBM;
			}
			set
			{
				if ((this._YZBM != value))
				{
					this.OnYZBMChanging(value);
					this.SendPropertyChanging();
					this._YZBM = value;
					this.SendPropertyChanged("YZBM");
					this.OnYZBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QYXZ", DbType="Char(1)")]
		public System.Nullable<char> QYXZ
		{
			get
			{
				return this._QYXZ;
			}
			set
			{
				if ((this._QYXZ != value))
				{
					this.OnQYXZChanging(value);
					this.SendPropertyChanging();
					this._QYXZ = value;
					this.SendPropertyChanged("QYXZ");
					this.OnQYXZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YWYY", DbType="VarChar(60)")]
		public string YWYY
		{
			get
			{
				return this._YWYY;
			}
			set
			{
				if ((this._YWYY != value))
				{
					this.OnYWYYChanging(value);
					this.SendPropertyChanging();
					this._YWYY = value;
					this.SendPropertyChanged("YWYY");
					this.OnYWYYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YHZH", DbType="VarChar(20)")]
		public string YHZH
		{
			get
			{
				return this._YHZH;
			}
			set
			{
				if ((this._YHZH != value))
				{
					this.OnYHZHChanging(value);
					this.SendPropertyChanging();
					this._YHZH = value;
					this.SendPropertyChanged("YHZH");
					this.OnYHZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JZRS", DbType="Int")]
		public System.Nullable<int> JZRS
		{
			get
			{
				return this._JZRS;
			}
			set
			{
				if ((this._JZRS != value))
				{
					this.OnJZRSChanging(value);
					this.SendPropertyChanging();
					this._JZRS = value;
					this.SendPropertyChanged("JZRS");
					this.OnJZRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LJZFJE", DbType="Float")]
		public System.Nullable<double> LJZFJE
		{
			get
			{
				return this._LJZFJE;
			}
			set
			{
				if ((this._LJZFJE != value))
				{
					this.OnLJZFJEChanging(value);
					this.SendPropertyChanging();
					this._LJZFJE = value;
					this.SendPropertyChanged("LJZFJE");
					this.OnLJZFJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LJZCJE", DbType="Float")]
		public System.Nullable<double> LJZCJE
		{
			get
			{
				return this._LJZCJE;
			}
			set
			{
				if ((this._LJZCJE != value))
				{
					this.OnLJZCJEChanging(value);
					this.SendPropertyChanging();
					this._LJZCJE = value;
					this.SendPropertyChanged("LJZCJE");
					this.OnLJZCJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(32)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZHXGR", DbType="Char(6)")]
		public string ZHXGR
		{
			get
			{
				return this._ZHXGR;
			}
			set
			{
				if ((this._ZHXGR != value))
				{
					this.OnZHXGRChanging(value);
					this.SendPropertyChanging();
					this._ZHXGR = value;
					this.SendPropertyChanged("ZHXGR");
					this.OnZHXGRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZHXGRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> ZHXGRQ
		{
			get
			{
				return this._ZHXGRQ;
			}
			set
			{
				if ((this._ZHXGRQ != value))
				{
					this.OnZHXGRQChanging(value);
					this.SendPropertyChanging();
					this._ZHXGRQ = value;
					this.SendPropertyChanged("ZHXGRQ");
					this.OnZHXGRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LB", DbType="Char(2)")]
		public string LB
		{
			get
			{
				return this._LB;
			}
			set
			{
				if ((this._LB != value))
				{
					this.OnLBChanging(value);
					this.SendPropertyChanging();
					this._LB = value;
					this.SendPropertyChanged("LB");
					this.OnLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZRS", DbType="Int")]
		public System.Nullable<int> BZRS
		{
			get
			{
				return this._BZRS;
			}
			set
			{
				if ((this._BZRS != value))
				{
					this.OnBZRSChanging(value);
					this.SendPropertyChanging();
					this._BZRS = value;
					this.SendPropertyChanged("BZRS");
					this.OnBZRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYJM", DbType="Char(10)")]
		public string PYJM
		{
			get
			{
				return this._PYJM;
			}
			set
			{
				if ((this._PYJM != value))
				{
					this.OnPYJMChanging(value);
					this.SendPropertyChanging();
					this._PYJM = value;
					this.SendPropertyChanged("PYJM");
					this.OnPYJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WBJM", DbType="Char(10)")]
		public string WBJM
		{
			get
			{
				return this._WBJM;
			}
			set
			{
				if ((this._WBJM != value))
				{
					this.OnWBJMChanging(value);
					this.SendPropertyChanging();
					this._WBJM = value;
					this.SendPropertyChanged("WBJM");
					this.OnWBJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QYBZ", DbType="Char(1)")]
		public System.Nullable<char> QYBZ
		{
			get
			{
				return this._QYBZ;
			}
			set
			{
				if ((this._QYBZ != value))
				{
					this.OnQYBZChanging(value);
					this.SendPropertyChanging();
					this._QYBZ = value;
					this.SendPropertyChanged("QYBZ");
					this.OnQYBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WJBZ", DbType="Char(1)")]
		public System.Nullable<char> WJBZ
		{
			get
			{
				return this._WJBZ;
			}
			set
			{
				if ((this._WJBZ != value))
				{
					this.OnWJBZChanging(value);
					this.SendPropertyChanging();
					this._WJBZ = value;
					this.SendPropertyChanged("WJBZ");
					this.OnWJBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HYDWDMB_TJ_TJDJB", Storage="_TJ_TJDJB", ThisKey="BH", OtherKey="DWBH")]
		public EntitySet<TJ_TJDJB> TJ_TJDJB
		{
			get
			{
				return this._TJ_TJDJB;
			}
			set
			{
				this._TJ_TJDJB.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TJ_TJDJB(TJ_TJDJB entity)
		{
			this.SendPropertyChanging();
			entity.HYDWDMB = this;
		}
		
		private void detach_TJ_TJDJB(TJ_TJDJB entity)
		{
			this.SendPropertyChanging();
			entity.HYDWDMB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="futian_user.GZRY")]
	public partial class GZRY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GKHM;
		
		private string _DYSRM;
		
		private string _DESRM;
		
		private string _GKMM;
		
		private string _PYJM;
		
		private string _WBJM;
		
		private string _QTSRF;
		
		private string _XM;
		
		private System.Nullable<System.DateTime> _CSRQ;
		
		private string _SFZHM;
		
		private System.Nullable<char> _CX;
		
		private string _QX;
		
		private string _ZW;
		
		private string _ZC;
		
		private string _GZKS;
		
		private string _GZBQ;
		
		private string _GZDZ;
		
		private string _BGSDH;
		
		private string _ZZ;
		
		private string _ZZDH;
		
		private string _CHHM;
		
		private char _SRF;
		
		private string _BZ;
		
		private System.DateTime _ZHXGRQ;
		
		private string _ZHXGR;
		
		private System.Nullable<char> _XB;
		
		private System.Nullable<char> _JB;
		
		private System.Nullable<char> _ZJYS;
		
		private System.Nullable<char> _QYBZ;
		
		private EntitySet<TJ_TJDJB> _TJ_TJDJB;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGKHMChanging(string value);
    partial void OnGKHMChanged();
    partial void OnDYSRMChanging(string value);
    partial void OnDYSRMChanged();
    partial void OnDESRMChanging(string value);
    partial void OnDESRMChanged();
    partial void OnGKMMChanging(string value);
    partial void OnGKMMChanged();
    partial void OnPYJMChanging(string value);
    partial void OnPYJMChanged();
    partial void OnWBJMChanging(string value);
    partial void OnWBJMChanged();
    partial void OnQTSRFChanging(string value);
    partial void OnQTSRFChanged();
    partial void OnXMChanging(string value);
    partial void OnXMChanged();
    partial void OnCSRQChanging(System.Nullable<System.DateTime> value);
    partial void OnCSRQChanged();
    partial void OnSFZHMChanging(string value);
    partial void OnSFZHMChanged();
    partial void OnCXChanging(System.Nullable<char> value);
    partial void OnCXChanged();
    partial void OnQXChanging(string value);
    partial void OnQXChanged();
    partial void OnZWChanging(string value);
    partial void OnZWChanged();
    partial void OnZCChanging(string value);
    partial void OnZCChanged();
    partial void OnGZKSChanging(string value);
    partial void OnGZKSChanged();
    partial void OnGZBQChanging(string value);
    partial void OnGZBQChanged();
    partial void OnGZDZChanging(string value);
    partial void OnGZDZChanged();
    partial void OnBGSDHChanging(string value);
    partial void OnBGSDHChanged();
    partial void OnZZChanging(string value);
    partial void OnZZChanged();
    partial void OnZZDHChanging(string value);
    partial void OnZZDHChanged();
    partial void OnCHHMChanging(string value);
    partial void OnCHHMChanged();
    partial void OnSRFChanging(char value);
    partial void OnSRFChanged();
    partial void OnBZChanging(string value);
    partial void OnBZChanged();
    partial void OnZHXGRQChanging(System.DateTime value);
    partial void OnZHXGRQChanged();
    partial void OnZHXGRChanging(string value);
    partial void OnZHXGRChanged();
    partial void OnXBChanging(System.Nullable<char> value);
    partial void OnXBChanged();
    partial void OnJBChanging(System.Nullable<char> value);
    partial void OnJBChanged();
    partial void OnZJYSChanging(System.Nullable<char> value);
    partial void OnZJYSChanged();
    partial void OnQYBZChanging(System.Nullable<char> value);
    partial void OnQYBZChanged();
    #endregion
		
		public GZRY()
		{
			this._TJ_TJDJB = new EntitySet<TJ_TJDJB>(new Action<TJ_TJDJB>(this.attach_TJ_TJDJB), new Action<TJ_TJDJB>(this.detach_TJ_TJDJB));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GKHM", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GKHM
		{
			get
			{
				return this._GKHM;
			}
			set
			{
				if ((this._GKHM != value))
				{
					this.OnGKHMChanging(value);
					this.SendPropertyChanging();
					this._GKHM = value;
					this.SendPropertyChanged("GKHM");
					this.OnGKHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DYSRM", DbType="Char(8)")]
		public string DYSRM
		{
			get
			{
				return this._DYSRM;
			}
			set
			{
				if ((this._DYSRM != value))
				{
					this.OnDYSRMChanging(value);
					this.SendPropertyChanging();
					this._DYSRM = value;
					this.SendPropertyChanged("DYSRM");
					this.OnDYSRMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESRM", DbType="Char(8)")]
		public string DESRM
		{
			get
			{
				return this._DESRM;
			}
			set
			{
				if ((this._DESRM != value))
				{
					this.OnDESRMChanging(value);
					this.SendPropertyChanging();
					this._DESRM = value;
					this.SendPropertyChanged("DESRM");
					this.OnDESRMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GKMM", DbType="Char(6)")]
		public string GKMM
		{
			get
			{
				return this._GKMM;
			}
			set
			{
				if ((this._GKMM != value))
				{
					this.OnGKMMChanging(value);
					this.SendPropertyChanging();
					this._GKMM = value;
					this.SendPropertyChanged("GKMM");
					this.OnGKMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYJM", DbType="Char(10)")]
		public string PYJM
		{
			get
			{
				return this._PYJM;
			}
			set
			{
				if ((this._PYJM != value))
				{
					this.OnPYJMChanging(value);
					this.SendPropertyChanging();
					this._PYJM = value;
					this.SendPropertyChanged("PYJM");
					this.OnPYJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WBJM", DbType="Char(4)")]
		public string WBJM
		{
			get
			{
				return this._WBJM;
			}
			set
			{
				if ((this._WBJM != value))
				{
					this.OnWBJMChanging(value);
					this.SendPropertyChanging();
					this._WBJM = value;
					this.SendPropertyChanged("WBJM");
					this.OnWBJMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTSRF", DbType="Char(10)")]
		public string QTSRF
		{
			get
			{
				return this._QTSRF;
			}
			set
			{
				if ((this._QTSRF != value))
				{
					this.OnQTSRFChanging(value);
					this.SendPropertyChanging();
					this._QTSRF = value;
					this.SendPropertyChanged("QTSRF");
					this.OnQTSRFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XM", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string XM
		{
			get
			{
				return this._XM;
			}
			set
			{
				if ((this._XM != value))
				{
					this.OnXMChanging(value);
					this.SendPropertyChanging();
					this._XM = value;
					this.SendPropertyChanged("XM");
					this.OnXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> CSRQ
		{
			get
			{
				return this._CSRQ;
			}
			set
			{
				if ((this._CSRQ != value))
				{
					this.OnCSRQChanging(value);
					this.SendPropertyChanging();
					this._CSRQ = value;
					this.SendPropertyChanged("CSRQ");
					this.OnCSRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFZHM", DbType="Char(15)")]
		public string SFZHM
		{
			get
			{
				return this._SFZHM;
			}
			set
			{
				if ((this._SFZHM != value))
				{
					this.OnSFZHMChanging(value);
					this.SendPropertyChanging();
					this._SFZHM = value;
					this.SendPropertyChanged("SFZHM");
					this.OnSFZHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CX", DbType="Char(1)")]
		public System.Nullable<char> CX
		{
			get
			{
				return this._CX;
			}
			set
			{
				if ((this._CX != value))
				{
					this.OnCXChanging(value);
					this.SendPropertyChanging();
					this._CX = value;
					this.SendPropertyChanged("CX");
					this.OnCXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QX", DbType="Char(30)")]
		public string QX
		{
			get
			{
				return this._QX;
			}
			set
			{
				if ((this._QX != value))
				{
					this.OnQXChanging(value);
					this.SendPropertyChanging();
					this._QX = value;
					this.SendPropertyChanged("QX");
					this.OnQXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZW", DbType="Char(14)")]
		public string ZW
		{
			get
			{
				return this._ZW;
			}
			set
			{
				if ((this._ZW != value))
				{
					this.OnZWChanging(value);
					this.SendPropertyChanging();
					this._ZW = value;
					this.SendPropertyChanged("ZW");
					this.OnZWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZC", DbType="Char(10)")]
		public string ZC
		{
			get
			{
				return this._ZC;
			}
			set
			{
				if ((this._ZC != value))
				{
					this.OnZCChanging(value);
					this.SendPropertyChanging();
					this._ZC = value;
					this.SendPropertyChanged("ZC");
					this.OnZCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZKS", DbType="Char(6)")]
		public string GZKS
		{
			get
			{
				return this._GZKS;
			}
			set
			{
				if ((this._GZKS != value))
				{
					this.OnGZKSChanging(value);
					this.SendPropertyChanging();
					this._GZKS = value;
					this.SendPropertyChanged("GZKS");
					this.OnGZKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZBQ", DbType="Char(2)")]
		public string GZBQ
		{
			get
			{
				return this._GZBQ;
			}
			set
			{
				if ((this._GZBQ != value))
				{
					this.OnGZBQChanging(value);
					this.SendPropertyChanging();
					this._GZBQ = value;
					this.SendPropertyChanged("GZBQ");
					this.OnGZBQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZDZ", DbType="VarChar(40)")]
		public string GZDZ
		{
			get
			{
				return this._GZDZ;
			}
			set
			{
				if ((this._GZDZ != value))
				{
					this.OnGZDZChanging(value);
					this.SendPropertyChanging();
					this._GZDZ = value;
					this.SendPropertyChanged("GZDZ");
					this.OnGZDZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGSDH", DbType="Char(15)")]
		public string BGSDH
		{
			get
			{
				return this._BGSDH;
			}
			set
			{
				if ((this._BGSDH != value))
				{
					this.OnBGSDHChanging(value);
					this.SendPropertyChanging();
					this._BGSDH = value;
					this.SendPropertyChanged("BGSDH");
					this.OnBGSDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZZ", DbType="VarChar(30)")]
		public string ZZ
		{
			get
			{
				return this._ZZ;
			}
			set
			{
				if ((this._ZZ != value))
				{
					this.OnZZChanging(value);
					this.SendPropertyChanging();
					this._ZZ = value;
					this.SendPropertyChanged("ZZ");
					this.OnZZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZZDH", DbType="Char(15)")]
		public string ZZDH
		{
			get
			{
				return this._ZZDH;
			}
			set
			{
				if ((this._ZZDH != value))
				{
					this.OnZZDHChanging(value);
					this.SendPropertyChanging();
					this._ZZDH = value;
					this.SendPropertyChanged("ZZDH");
					this.OnZZDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHHM", DbType="Char(20)")]
		public string CHHM
		{
			get
			{
				return this._CHHM;
			}
			set
			{
				if ((this._CHHM != value))
				{
					this.OnCHHMChanging(value);
					this.SendPropertyChanging();
					this._CHHM = value;
					this.SendPropertyChanged("CHHM");
					this.OnCHHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRF", DbType="Char(1) NOT NULL")]
		public char SRF
		{
			get
			{
				return this._SRF;
			}
			set
			{
				if ((this._SRF != value))
				{
					this.OnSRFChanging(value);
					this.SendPropertyChanging();
					this._SRF = value;
					this.SendPropertyChanged("SRF");
					this.OnSRFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZ", DbType="VarChar(64)")]
		public string BZ
		{
			get
			{
				return this._BZ;
			}
			set
			{
				if ((this._BZ != value))
				{
					this.OnBZChanging(value);
					this.SendPropertyChanging();
					this._BZ = value;
					this.SendPropertyChanged("BZ");
					this.OnBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZHXGRQ", DbType="DateTime NOT NULL")]
		public System.DateTime ZHXGRQ
		{
			get
			{
				return this._ZHXGRQ;
			}
			set
			{
				if ((this._ZHXGRQ != value))
				{
					this.OnZHXGRQChanging(value);
					this.SendPropertyChanging();
					this._ZHXGRQ = value;
					this.SendPropertyChanged("ZHXGRQ");
					this.OnZHXGRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZHXGR", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string ZHXGR
		{
			get
			{
				return this._ZHXGR;
			}
			set
			{
				if ((this._ZHXGR != value))
				{
					this.OnZHXGRChanging(value);
					this.SendPropertyChanging();
					this._ZHXGR = value;
					this.SendPropertyChanged("ZHXGR");
					this.OnZHXGRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XB", DbType="Char(1)")]
		public System.Nullable<char> XB
		{
			get
			{
				return this._XB;
			}
			set
			{
				if ((this._XB != value))
				{
					this.OnXBChanging(value);
					this.SendPropertyChanging();
					this._XB = value;
					this.SendPropertyChanged("XB");
					this.OnXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JB", DbType="Char(1)")]
		public System.Nullable<char> JB
		{
			get
			{
				return this._JB;
			}
			set
			{
				if ((this._JB != value))
				{
					this.OnJBChanging(value);
					this.SendPropertyChanging();
					this._JB = value;
					this.SendPropertyChanged("JB");
					this.OnJBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZJYS", DbType="Char(1)")]
		public System.Nullable<char> ZJYS
		{
			get
			{
				return this._ZJYS;
			}
			set
			{
				if ((this._ZJYS != value))
				{
					this.OnZJYSChanging(value);
					this.SendPropertyChanging();
					this._ZJYS = value;
					this.SendPropertyChanged("ZJYS");
					this.OnZJYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QYBZ", DbType="Char(1)")]
		public System.Nullable<char> QYBZ
		{
			get
			{
				return this._QYBZ;
			}
			set
			{
				if ((this._QYBZ != value))
				{
					this.OnQYBZChanging(value);
					this.SendPropertyChanging();
					this._QYBZ = value;
					this.SendPropertyChanged("QYBZ");
					this.OnQYBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GZRY_TJ_TJDJB", Storage="_TJ_TJDJB", ThisKey="GKHM", OtherKey="JCYS")]
		public EntitySet<TJ_TJDJB> TJ_TJDJB
		{
			get
			{
				return this._TJ_TJDJB;
			}
			set
			{
				this._TJ_TJDJB.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TJ_TJDJB(TJ_TJDJB entity)
		{
			this.SendPropertyChanging();
			entity.GZRY = this;
		}
		
		private void detach_TJ_TJDJB(TJ_TJDJB entity)
		{
			this.SendPropertyChanging();
			entity.GZRY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="futian_user.TJ_TJDJB")]
	public partial class TJ_TJDJB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TJBH;
		
		private int _TJCS;
		
		private string _XM;
		
		private System.Nullable<char> _XB;
		
		private System.Nullable<int> _NL;
		
		private string _DWBH;
		
		private System.DateTime _TJRQ;
		
		private System.DateTime _DJRQ;
		
		private string _DJRY;
		
		private string _ZS;
		
		private string _JY;
		
		private System.Nullable<System.DateTime> _JCRQ;
		
		private string _JCYS;
		
		private System.Nullable<System.DateTime> _GDRQ;
		
		private string _GDYS;
		
		private string _SFZH;
		
		private string _ZC;
		
		private string _ZW;
		
		private string _TJLB;
		
		private string _RYLB;
		
		private System.Nullable<char> _HYZK;
		
		private System.Nullable<char> _FZFS;
		
		private string _FZBH;
		
		private char _JSFS;
		
		private string _YYBH;
		
		private char _SUMOVER;
		
		private string _DEPART;
		
		private string _DJLSH;
		
		private string _RYBH;
		
		private string _ADDRESS;
		
		private string _PHONE;
		
		private string _BMBH;
		
		private string _SJCXXH;
		
		private System.Nullable<System.DateTime> _FCRQ;
		
		private System.Nullable<int> _FCTS;
		
		private string _FCGY;
		
		private System.Nullable<System.DateTime> _CSRQ;
		
		private System.Nullable<char> _TJBZ;
		
		private System.Nullable<int> _AGE;
		
		private System.Nullable<System.DateTime> _FZRQ;
		
		private string _FZDW;
		
		private System.Data.Linq.Binary _PICTURE;
		
		private string _BZR;
		
		private System.Nullable<System.DateTime> _CSNYR;
		
		private System.Nullable<System.DateTime> _GZRQ;
		
		private string _JCSJ;
		
		private string _BM;
		
		private string _GZ;
		
		private string _YHYS;
		
		private System.Nullable<char> _WHCD;
		
		private string _ZDYJ;
		
		private System.Nullable<char> _SFTZ;
		
		private System.Nullable<char> _TZQK;
		
		private string _TZR;
		
		private System.Nullable<int> _YF;
		
		private System.Nullable<int> _DYCS;
		
		private string _MOBILE;
		
		private string _EMAIL;
		
		private System.Nullable<char> _SV_CALLBACK;
		
		private System.Nullable<char> _SV_SMS;
		
		private System.Nullable<char> _SV_EMAIL;
		
		private System.Nullable<char> _SV_WEB;
		
		private EntityRef<HYDWDMB> _HYDWDMB;
		
		private EntityRef<GZRY> _GZRY;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTJBHChanging(string value);
    partial void OnTJBHChanged();
    partial void OnTJCSChanging(int value);
    partial void OnTJCSChanged();
    partial void OnXMChanging(string value);
    partial void OnXMChanged();
    partial void OnXBChanging(System.Nullable<char> value);
    partial void OnXBChanged();
    partial void OnNLChanging(System.Nullable<int> value);
    partial void OnNLChanged();
    partial void OnDWBHChanging(string value);
    partial void OnDWBHChanged();
    partial void OnTJRQChanging(System.DateTime value);
    partial void OnTJRQChanged();
    partial void OnDJRQChanging(System.DateTime value);
    partial void OnDJRQChanged();
    partial void OnDJRYChanging(string value);
    partial void OnDJRYChanged();
    partial void OnZSChanging(string value);
    partial void OnZSChanged();
    partial void OnJYChanging(string value);
    partial void OnJYChanged();
    partial void OnJCRQChanging(System.Nullable<System.DateTime> value);
    partial void OnJCRQChanged();
    partial void OnJCYSChanging(string value);
    partial void OnJCYSChanged();
    partial void OnGDRQChanging(System.Nullable<System.DateTime> value);
    partial void OnGDRQChanged();
    partial void OnGDYSChanging(string value);
    partial void OnGDYSChanged();
    partial void OnSFZHChanging(string value);
    partial void OnSFZHChanged();
    partial void OnZCChanging(string value);
    partial void OnZCChanged();
    partial void OnZWChanging(string value);
    partial void OnZWChanged();
    partial void OnTJLBChanging(string value);
    partial void OnTJLBChanged();
    partial void OnRYLBChanging(string value);
    partial void OnRYLBChanged();
    partial void OnHYZKChanging(System.Nullable<char> value);
    partial void OnHYZKChanged();
    partial void OnFZFSChanging(System.Nullable<char> value);
    partial void OnFZFSChanged();
    partial void OnFZBHChanging(string value);
    partial void OnFZBHChanged();
    partial void OnJSFSChanging(char value);
    partial void OnJSFSChanged();
    partial void OnYYBHChanging(string value);
    partial void OnYYBHChanged();
    partial void OnSUMOVERChanging(char value);
    partial void OnSUMOVERChanged();
    partial void OnDEPARTChanging(string value);
    partial void OnDEPARTChanged();
    partial void OnDJLSHChanging(string value);
    partial void OnDJLSHChanged();
    partial void OnRYBHChanging(string value);
    partial void OnRYBHChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnPHONEChanging(string value);
    partial void OnPHONEChanged();
    partial void OnBMBHChanging(string value);
    partial void OnBMBHChanged();
    partial void OnSJCXXHChanging(string value);
    partial void OnSJCXXHChanged();
    partial void OnFCRQChanging(System.Nullable<System.DateTime> value);
    partial void OnFCRQChanged();
    partial void OnFCTSChanging(System.Nullable<int> value);
    partial void OnFCTSChanged();
    partial void OnFCGYChanging(string value);
    partial void OnFCGYChanged();
    partial void OnCSRQChanging(System.Nullable<System.DateTime> value);
    partial void OnCSRQChanged();
    partial void OnTJBZChanging(System.Nullable<char> value);
    partial void OnTJBZChanged();
    partial void OnAGEChanging(System.Nullable<int> value);
    partial void OnAGEChanged();
    partial void OnFZRQChanging(System.Nullable<System.DateTime> value);
    partial void OnFZRQChanged();
    partial void OnFZDWChanging(string value);
    partial void OnFZDWChanged();
    partial void OnPICTUREChanging(System.Data.Linq.Binary value);
    partial void OnPICTUREChanged();
    partial void OnBZRChanging(string value);
    partial void OnBZRChanged();
    partial void OnCSNYRChanging(System.Nullable<System.DateTime> value);
    partial void OnCSNYRChanged();
    partial void OnGZRQChanging(System.Nullable<System.DateTime> value);
    partial void OnGZRQChanged();
    partial void OnJCSJChanging(string value);
    partial void OnJCSJChanged();
    partial void OnBMChanging(string value);
    partial void OnBMChanged();
    partial void OnGZChanging(string value);
    partial void OnGZChanged();
    partial void OnYHYSChanging(string value);
    partial void OnYHYSChanged();
    partial void OnWHCDChanging(System.Nullable<char> value);
    partial void OnWHCDChanged();
    partial void OnZDYJChanging(string value);
    partial void OnZDYJChanged();
    partial void OnSFTZChanging(System.Nullable<char> value);
    partial void OnSFTZChanged();
    partial void OnTZQKChanging(System.Nullable<char> value);
    partial void OnTZQKChanged();
    partial void OnTZRChanging(string value);
    partial void OnTZRChanged();
    partial void OnYFChanging(System.Nullable<int> value);
    partial void OnYFChanged();
    partial void OnDYCSChanging(System.Nullable<int> value);
    partial void OnDYCSChanged();
    partial void OnMOBILEChanging(string value);
    partial void OnMOBILEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSV_CALLBACKChanging(System.Nullable<char> value);
    partial void OnSV_CALLBACKChanged();
    partial void OnSV_SMSChanging(System.Nullable<char> value);
    partial void OnSV_SMSChanged();
    partial void OnSV_EMAILChanging(System.Nullable<char> value);
    partial void OnSV_EMAILChanged();
    partial void OnSV_WEBChanging(System.Nullable<char> value);
    partial void OnSV_WEBChanged();
    #endregion
		
		public TJ_TJDJB()
		{
			this._HYDWDMB = default(EntityRef<HYDWDMB>);
			this._GZRY = default(EntityRef<GZRY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJBH", DbType="VarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TJBH
		{
			get
			{
				return this._TJBH;
			}
			set
			{
				if ((this._TJBH != value))
				{
					this.OnTJBHChanging(value);
					this.SendPropertyChanging();
					this._TJBH = value;
					this.SendPropertyChanged("TJBH");
					this.OnTJBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJCS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TJCS
		{
			get
			{
				return this._TJCS;
			}
			set
			{
				if ((this._TJCS != value))
				{
					this.OnTJCSChanging(value);
					this.SendPropertyChanging();
					this._TJCS = value;
					this.SendPropertyChanged("TJCS");
					this.OnTJCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XM", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string XM
		{
			get
			{
				return this._XM;
			}
			set
			{
				if ((this._XM != value))
				{
					this.OnXMChanging(value);
					this.SendPropertyChanging();
					this._XM = value;
					this.SendPropertyChanged("XM");
					this.OnXMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XB", DbType="Char(1)")]
		public System.Nullable<char> XB
		{
			get
			{
				return this._XB;
			}
			set
			{
				if ((this._XB != value))
				{
					this.OnXBChanging(value);
					this.SendPropertyChanging();
					this._XB = value;
					this.SendPropertyChanged("XB");
					this.OnXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NL", DbType="Int")]
		public System.Nullable<int> NL
		{
			get
			{
				return this._NL;
			}
			set
			{
				if ((this._NL != value))
				{
					this.OnNLChanging(value);
					this.SendPropertyChanging();
					this._NL = value;
					this.SendPropertyChanged("NL");
					this.OnNLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWBH", DbType="VarChar(25)")]
		public string DWBH
		{
			get
			{
				return this._DWBH;
			}
			set
			{
				if ((this._DWBH != value))
				{
					if (this._HYDWDMB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDWBHChanging(value);
					this.SendPropertyChanging();
					this._DWBH = value;
					this.SendPropertyChanged("DWBH");
					this.OnDWBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJRQ", DbType="DateTime NOT NULL")]
		public System.DateTime TJRQ
		{
			get
			{
				return this._TJRQ;
			}
			set
			{
				if ((this._TJRQ != value))
				{
					this.OnTJRQChanging(value);
					this.SendPropertyChanging();
					this._TJRQ = value;
					this.SendPropertyChanged("TJRQ");
					this.OnTJRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DJRQ", DbType="DateTime NOT NULL")]
		public System.DateTime DJRQ
		{
			get
			{
				return this._DJRQ;
			}
			set
			{
				if ((this._DJRQ != value))
				{
					this.OnDJRQChanging(value);
					this.SendPropertyChanging();
					this._DJRQ = value;
					this.SendPropertyChanged("DJRQ");
					this.OnDJRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DJRY", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string DJRY
		{
			get
			{
				return this._DJRY;
			}
			set
			{
				if ((this._DJRY != value))
				{
					this.OnDJRYChanging(value);
					this.SendPropertyChanging();
					this._DJRY = value;
					this.SendPropertyChanged("DJRY");
					this.OnDJRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZS", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ZS
		{
			get
			{
				return this._ZS;
			}
			set
			{
				if ((this._ZS != value))
				{
					this.OnZSChanging(value);
					this.SendPropertyChanging();
					this._ZS = value;
					this.SendPropertyChanged("ZS");
					this.OnZSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JY", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string JY
		{
			get
			{
				return this._JY;
			}
			set
			{
				if ((this._JY != value))
				{
					this.OnJYChanging(value);
					this.SendPropertyChanging();
					this._JY = value;
					this.SendPropertyChanged("JY");
					this.OnJYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JCRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> JCRQ
		{
			get
			{
				return this._JCRQ;
			}
			set
			{
				if ((this._JCRQ != value))
				{
					this.OnJCRQChanging(value);
					this.SendPropertyChanging();
					this._JCRQ = value;
					this.SendPropertyChanged("JCRQ");
					this.OnJCRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JCYS", DbType="Char(6)")]
		public string JCYS
		{
			get
			{
				return this._JCYS;
			}
			set
			{
				if ((this._JCYS != value))
				{
					if (this._GZRY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnJCYSChanging(value);
					this.SendPropertyChanging();
					this._JCYS = value;
					this.SendPropertyChanged("JCYS");
					this.OnJCYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> GDRQ
		{
			get
			{
				return this._GDRQ;
			}
			set
			{
				if ((this._GDRQ != value))
				{
					this.OnGDRQChanging(value);
					this.SendPropertyChanging();
					this._GDRQ = value;
					this.SendPropertyChanged("GDRQ");
					this.OnGDRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDYS", DbType="Char(6)")]
		public string GDYS
		{
			get
			{
				return this._GDYS;
			}
			set
			{
				if ((this._GDYS != value))
				{
					this.OnGDYSChanging(value);
					this.SendPropertyChanging();
					this._GDYS = value;
					this.SendPropertyChanged("GDYS");
					this.OnGDYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFZH", DbType="VarChar(18)")]
		public string SFZH
		{
			get
			{
				return this._SFZH;
			}
			set
			{
				if ((this._SFZH != value))
				{
					this.OnSFZHChanging(value);
					this.SendPropertyChanging();
					this._SFZH = value;
					this.SendPropertyChanged("SFZH");
					this.OnSFZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZC", DbType="VarChar(16)")]
		public string ZC
		{
			get
			{
				return this._ZC;
			}
			set
			{
				if ((this._ZC != value))
				{
					this.OnZCChanging(value);
					this.SendPropertyChanging();
					this._ZC = value;
					this.SendPropertyChanged("ZC");
					this.OnZCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZW", DbType="VarChar(16)")]
		public string ZW
		{
			get
			{
				return this._ZW;
			}
			set
			{
				if ((this._ZW != value))
				{
					this.OnZWChanging(value);
					this.SendPropertyChanging();
					this._ZW = value;
					this.SendPropertyChanged("ZW");
					this.OnZWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJLB", DbType="Char(2)")]
		public string TJLB
		{
			get
			{
				return this._TJLB;
			}
			set
			{
				if ((this._TJLB != value))
				{
					this.OnTJLBChanging(value);
					this.SendPropertyChanging();
					this._TJLB = value;
					this.SendPropertyChanged("TJLB");
					this.OnTJLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYLB", DbType="Char(2)")]
		public string RYLB
		{
			get
			{
				return this._RYLB;
			}
			set
			{
				if ((this._RYLB != value))
				{
					this.OnRYLBChanging(value);
					this.SendPropertyChanging();
					this._RYLB = value;
					this.SendPropertyChanged("RYLB");
					this.OnRYLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HYZK", DbType="Char(1)")]
		public System.Nullable<char> HYZK
		{
			get
			{
				return this._HYZK;
			}
			set
			{
				if ((this._HYZK != value))
				{
					this.OnHYZKChanging(value);
					this.SendPropertyChanging();
					this._HYZK = value;
					this.SendPropertyChanged("HYZK");
					this.OnHYZKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FZFS", DbType="Char(1)")]
		public System.Nullable<char> FZFS
		{
			get
			{
				return this._FZFS;
			}
			set
			{
				if ((this._FZFS != value))
				{
					this.OnFZFSChanging(value);
					this.SendPropertyChanging();
					this._FZFS = value;
					this.SendPropertyChanged("FZFS");
					this.OnFZFSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FZBH", DbType="Char(6)")]
		public string FZBH
		{
			get
			{
				return this._FZBH;
			}
			set
			{
				if ((this._FZBH != value))
				{
					this.OnFZBHChanging(value);
					this.SendPropertyChanging();
					this._FZBH = value;
					this.SendPropertyChanged("FZBH");
					this.OnFZBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSFS", DbType="Char(1) NOT NULL")]
		public char JSFS
		{
			get
			{
				return this._JSFS;
			}
			set
			{
				if ((this._JSFS != value))
				{
					this.OnJSFSChanging(value);
					this.SendPropertyChanging();
					this._JSFS = value;
					this.SendPropertyChanged("JSFS");
					this.OnJSFSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYBH", DbType="Char(16)")]
		public string YYBH
		{
			get
			{
				return this._YYBH;
			}
			set
			{
				if ((this._YYBH != value))
				{
					this.OnYYBHChanging(value);
					this.SendPropertyChanging();
					this._YYBH = value;
					this.SendPropertyChanged("YYBH");
					this.OnYYBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMOVER", DbType="Char(1) NOT NULL")]
		public char SUMOVER
		{
			get
			{
				return this._SUMOVER;
			}
			set
			{
				if ((this._SUMOVER != value))
				{
					this.OnSUMOVERChanging(value);
					this.SendPropertyChanging();
					this._SUMOVER = value;
					this.SendPropertyChanged("SUMOVER");
					this.OnSUMOVERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPART", DbType="VarChar(64)")]
		public string DEPART
		{
			get
			{
				return this._DEPART;
			}
			set
			{
				if ((this._DEPART != value))
				{
					this.OnDEPARTChanging(value);
					this.SendPropertyChanging();
					this._DEPART = value;
					this.SendPropertyChanged("DEPART");
					this.OnDEPARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DJLSH", DbType="Char(12)")]
		public string DJLSH
		{
			get
			{
				return this._DJLSH;
			}
			set
			{
				if ((this._DJLSH != value))
				{
					this.OnDJLSHChanging(value);
					this.SendPropertyChanging();
					this._DJLSH = value;
					this.SendPropertyChanged("DJLSH");
					this.OnDJLSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYBH", DbType="VarChar(10)")]
		public string RYBH
		{
			get
			{
				return this._RYBH;
			}
			set
			{
				if ((this._RYBH != value))
				{
					this.OnRYBHChanging(value);
					this.SendPropertyChanging();
					this._RYBH = value;
					this.SendPropertyChanged("RYBH");
					this.OnRYBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(128)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(32)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMBH", DbType="Char(12)")]
		public string BMBH
		{
			get
			{
				return this._BMBH;
			}
			set
			{
				if ((this._BMBH != value))
				{
					this.OnBMBHChanging(value);
					this.SendPropertyChanging();
					this._BMBH = value;
					this.SendPropertyChanged("BMBH");
					this.OnBMBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SJCXXH", DbType="VarChar(12)")]
		public string SJCXXH
		{
			get
			{
				return this._SJCXXH;
			}
			set
			{
				if ((this._SJCXXH != value))
				{
					this.OnSJCXXHChanging(value);
					this.SendPropertyChanging();
					this._SJCXXH = value;
					this.SendPropertyChanged("SJCXXH");
					this.OnSJCXXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> FCRQ
		{
			get
			{
				return this._FCRQ;
			}
			set
			{
				if ((this._FCRQ != value))
				{
					this.OnFCRQChanging(value);
					this.SendPropertyChanging();
					this._FCRQ = value;
					this.SendPropertyChanged("FCRQ");
					this.OnFCRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCTS", DbType="Int")]
		public System.Nullable<int> FCTS
		{
			get
			{
				return this._FCTS;
			}
			set
			{
				if ((this._FCTS != value))
				{
					this.OnFCTSChanging(value);
					this.SendPropertyChanging();
					this._FCTS = value;
					this.SendPropertyChanged("FCTS");
					this.OnFCTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCGY", DbType="VarChar(64)")]
		public string FCGY
		{
			get
			{
				return this._FCGY;
			}
			set
			{
				if ((this._FCGY != value))
				{
					this.OnFCGYChanging(value);
					this.SendPropertyChanging();
					this._FCGY = value;
					this.SendPropertyChanged("FCGY");
					this.OnFCGYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> CSRQ
		{
			get
			{
				return this._CSRQ;
			}
			set
			{
				if ((this._CSRQ != value))
				{
					this.OnCSRQChanging(value);
					this.SendPropertyChanging();
					this._CSRQ = value;
					this.SendPropertyChanged("CSRQ");
					this.OnCSRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TJBZ", DbType="Char(1)")]
		public System.Nullable<char> TJBZ
		{
			get
			{
				return this._TJBZ;
			}
			set
			{
				if ((this._TJBZ != value))
				{
					this.OnTJBZChanging(value);
					this.SendPropertyChanging();
					this._TJBZ = value;
					this.SendPropertyChanged("TJBZ");
					this.OnTJBZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
		public System.Nullable<int> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this.OnAGEChanging(value);
					this.SendPropertyChanging();
					this._AGE = value;
					this.SendPropertyChanged("AGE");
					this.OnAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FZRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> FZRQ
		{
			get
			{
				return this._FZRQ;
			}
			set
			{
				if ((this._FZRQ != value))
				{
					this.OnFZRQChanging(value);
					this.SendPropertyChanging();
					this._FZRQ = value;
					this.SendPropertyChanged("FZRQ");
					this.OnFZRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FZDW", DbType="Char(40)")]
		public string FZDW
		{
			get
			{
				return this._FZDW;
			}
			set
			{
				if ((this._FZDW != value))
				{
					this.OnFZDWChanging(value);
					this.SendPropertyChanging();
					this._FZDW = value;
					this.SendPropertyChanged("FZDW");
					this.OnFZDWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICTURE", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PICTURE
		{
			get
			{
				return this._PICTURE;
			}
			set
			{
				if ((this._PICTURE != value))
				{
					this.OnPICTUREChanging(value);
					this.SendPropertyChanging();
					this._PICTURE = value;
					this.SendPropertyChanged("PICTURE");
					this.OnPICTUREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZR", DbType="Char(12)")]
		public string BZR
		{
			get
			{
				return this._BZR;
			}
			set
			{
				if ((this._BZR != value))
				{
					this.OnBZRChanging(value);
					this.SendPropertyChanging();
					this._BZR = value;
					this.SendPropertyChanged("BZR");
					this.OnBZRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSNYR", DbType="DateTime")]
		public System.Nullable<System.DateTime> CSNYR
		{
			get
			{
				return this._CSNYR;
			}
			set
			{
				if ((this._CSNYR != value))
				{
					this.OnCSNYRChanging(value);
					this.SendPropertyChanging();
					this._CSNYR = value;
					this.SendPropertyChanged("CSNYR");
					this.OnCSNYRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZRQ", DbType="DateTime")]
		public System.Nullable<System.DateTime> GZRQ
		{
			get
			{
				return this._GZRQ;
			}
			set
			{
				if ((this._GZRQ != value))
				{
					this.OnGZRQChanging(value);
					this.SendPropertyChanging();
					this._GZRQ = value;
					this.SendPropertyChanged("GZRQ");
					this.OnGZRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JCSJ", DbType="VarChar(4)")]
		public string JCSJ
		{
			get
			{
				return this._JCSJ;
			}
			set
			{
				if ((this._JCSJ != value))
				{
					this.OnJCSJChanging(value);
					this.SendPropertyChanging();
					this._JCSJ = value;
					this.SendPropertyChanged("JCSJ");
					this.OnJCSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM", DbType="VarChar(32)")]
		public string BM
		{
			get
			{
				return this._BM;
			}
			set
			{
				if ((this._BM != value))
				{
					this.OnBMChanging(value);
					this.SendPropertyChanging();
					this._BM = value;
					this.SendPropertyChanged("BM");
					this.OnBMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GZ", DbType="VarChar(10)")]
		public string GZ
		{
			get
			{
				return this._GZ;
			}
			set
			{
				if ((this._GZ != value))
				{
					this.OnGZChanging(value);
					this.SendPropertyChanging();
					this._GZ = value;
					this.SendPropertyChanged("GZ");
					this.OnGZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YHYS", DbType="VarChar(24)")]
		public string YHYS
		{
			get
			{
				return this._YHYS;
			}
			set
			{
				if ((this._YHYS != value))
				{
					this.OnYHYSChanging(value);
					this.SendPropertyChanging();
					this._YHYS = value;
					this.SendPropertyChanged("YHYS");
					this.OnYHYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHCD", DbType="Char(1)")]
		public System.Nullable<char> WHCD
		{
			get
			{
				return this._WHCD;
			}
			set
			{
				if ((this._WHCD != value))
				{
					this.OnWHCDChanging(value);
					this.SendPropertyChanging();
					this._WHCD = value;
					this.SendPropertyChanged("WHCD");
					this.OnWHCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZDYJ", DbType="VarChar(50)")]
		public string ZDYJ
		{
			get
			{
				return this._ZDYJ;
			}
			set
			{
				if ((this._ZDYJ != value))
				{
					this.OnZDYJChanging(value);
					this.SendPropertyChanging();
					this._ZDYJ = value;
					this.SendPropertyChanged("ZDYJ");
					this.OnZDYJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFTZ", DbType="Char(1)")]
		public System.Nullable<char> SFTZ
		{
			get
			{
				return this._SFTZ;
			}
			set
			{
				if ((this._SFTZ != value))
				{
					this.OnSFTZChanging(value);
					this.SendPropertyChanging();
					this._SFTZ = value;
					this.SendPropertyChanged("SFTZ");
					this.OnSFTZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TZQK", DbType="Char(1)")]
		public System.Nullable<char> TZQK
		{
			get
			{
				return this._TZQK;
			}
			set
			{
				if ((this._TZQK != value))
				{
					this.OnTZQKChanging(value);
					this.SendPropertyChanging();
					this._TZQK = value;
					this.SendPropertyChanged("TZQK");
					this.OnTZQKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TZR", DbType="Char(12)")]
		public string TZR
		{
			get
			{
				return this._TZR;
			}
			set
			{
				if ((this._TZR != value))
				{
					this.OnTZRChanging(value);
					this.SendPropertyChanging();
					this._TZR = value;
					this.SendPropertyChanged("TZR");
					this.OnTZRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YF", DbType="Int")]
		public System.Nullable<int> YF
		{
			get
			{
				return this._YF;
			}
			set
			{
				if ((this._YF != value))
				{
					this.OnYFChanging(value);
					this.SendPropertyChanging();
					this._YF = value;
					this.SendPropertyChanged("YF");
					this.OnYFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DYCS", DbType="Int")]
		public System.Nullable<int> DYCS
		{
			get
			{
				return this._DYCS;
			}
			set
			{
				if ((this._DYCS != value))
				{
					this.OnDYCSChanging(value);
					this.SendPropertyChanging();
					this._DYCS = value;
					this.SendPropertyChanged("DYCS");
					this.OnDYCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE", DbType="VarChar(15)")]
		public string MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this.OnMOBILEChanging(value);
					this.SendPropertyChanging();
					this._MOBILE = value;
					this.SendPropertyChanged("MOBILE");
					this.OnMOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV_CALLBACK", DbType="Char(1)")]
		public System.Nullable<char> SV_CALLBACK
		{
			get
			{
				return this._SV_CALLBACK;
			}
			set
			{
				if ((this._SV_CALLBACK != value))
				{
					this.OnSV_CALLBACKChanging(value);
					this.SendPropertyChanging();
					this._SV_CALLBACK = value;
					this.SendPropertyChanged("SV_CALLBACK");
					this.OnSV_CALLBACKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV_SMS", DbType="Char(1)")]
		public System.Nullable<char> SV_SMS
		{
			get
			{
				return this._SV_SMS;
			}
			set
			{
				if ((this._SV_SMS != value))
				{
					this.OnSV_SMSChanging(value);
					this.SendPropertyChanging();
					this._SV_SMS = value;
					this.SendPropertyChanged("SV_SMS");
					this.OnSV_SMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV_EMAIL", DbType="Char(1)")]
		public System.Nullable<char> SV_EMAIL
		{
			get
			{
				return this._SV_EMAIL;
			}
			set
			{
				if ((this._SV_EMAIL != value))
				{
					this.OnSV_EMAILChanging(value);
					this.SendPropertyChanging();
					this._SV_EMAIL = value;
					this.SendPropertyChanged("SV_EMAIL");
					this.OnSV_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV_WEB", DbType="Char(1)")]
		public System.Nullable<char> SV_WEB
		{
			get
			{
				return this._SV_WEB;
			}
			set
			{
				if ((this._SV_WEB != value))
				{
					this.OnSV_WEBChanging(value);
					this.SendPropertyChanging();
					this._SV_WEB = value;
					this.SendPropertyChanged("SV_WEB");
					this.OnSV_WEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HYDWDMB_TJ_TJDJB", Storage="_HYDWDMB", ThisKey="DWBH", OtherKey="BH", IsForeignKey=true)]
		public HYDWDMB HYDWDMB
		{
			get
			{
				return this._HYDWDMB.Entity;
			}
			set
			{
				HYDWDMB previousValue = this._HYDWDMB.Entity;
				if (((previousValue != value) 
							|| (this._HYDWDMB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HYDWDMB.Entity = null;
						previousValue.TJ_TJDJB.Remove(this);
					}
					this._HYDWDMB.Entity = value;
					if ((value != null))
					{
						value.TJ_TJDJB.Add(this);
						this._DWBH = value.BH;
					}
					else
					{
						this._DWBH = default(string);
					}
					this.SendPropertyChanged("HYDWDMB");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GZRY_TJ_TJDJB", Storage="_GZRY", ThisKey="JCYS", OtherKey="GKHM", IsForeignKey=true)]
		public GZRY GZRY
		{
			get
			{
				return this._GZRY.Entity;
			}
			set
			{
				GZRY previousValue = this._GZRY.Entity;
				if (((previousValue != value) 
							|| (this._GZRY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GZRY.Entity = null;
						previousValue.TJ_TJDJB.Remove(this);
					}
					this._GZRY.Entity = value;
					if ((value != null))
					{
						value.TJ_TJDJB.Add(this);
						this._JCYS = value.GKHM;
					}
					else
					{
						this._JCYS = default(string);
					}
					this.SendPropertyChanged("GZRY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
